version: '3.1'

services:
    postgres:
        image: postgres:10.7-alpine
        container_name: scalikejdbc-postgres-test
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=test
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
        driver: local
